### ISSUE TITLE
Godhosts plugin displays errors on Vagrant projects that do not use it

### ISSUE THREAD

**Issue by tomjn** [goodhosts/vagrant#10]
I have a Chassis project that relies on Bonjour/Avahi for host names, but when I run `vagrant up` the goodhosts plugin intervenes and displays this error message:

```
==> default: [vagrant-goodhosts] Checking for host entries
==> default: [vagrant-goodhosts] Error adding some hosts, no IP was provided for the following hostnames: 
```

My expectation is that projects that don't use goodhosts would not trigger the goodhosts plugin

**Comment by Mte90** [comment]
It is the same of https://github.com/goodhosts/vagrant/issues/8

Basically hostsupdater had this behaviour, add automatically the machine name with an ip in the hosts file.

So I think that can be an handy feature but I can remove it.

**Comment by tomjn** [comment]
I'd remove it, it's useful if you intended to use goodhosts and didn't set it up right but for other projects it's frustrating
