### ISSUE TITLE
Goodhosts reorders my hosts file

### ISSUE THREAD

**Issue by janw-me** [goodhosts/vagrant#12]
I always put a lot of excpetions in my hostfile, mostly for temporary switching server.
So I also quote them out a lot.

Yesterday I ran `vagrant plugin update` and it updated to 1.0.7 and I suspended vvv.
Today I start up to see my whole hostfile is reorder alphabetical _and_ the lines that where commented out are removed.

So I rearange them a bit for a test, run `vagrant up` and its all reordered agian.

I'm on Ubuntu 20.04

**Comment by Mte90** [comment]
This is the behavior of https://github.com/goodhosts/cli with the new cli command that we integrated that include cleaning.

**Comment by janw-me** [comment]
Okay, but is there a way to disable it?
I'd like to keep my structure

**Comment by Mte90** [comment]
using an old version of the plugin like https://github.com/goodhosts/vagrant/releases/tag/1.0.4 that doesn't include that feature in the meantime is the best way.

**Comment by janw-me** [comment]
Okay I'll downgrade

**Comment by Mte90** [comment]
new parameter added to disable cleaning
