### ISSUE TITLE
Plugin complains about IP despite not being used

### ISSUE THREAD

**Issue by tomjn** [goodhosts/vagrant#14]
I have a Vagrant environment that uses no hostsupdater or goodhosts. It relies on bonjour/zeroconf for domains, not the hosts file.

Yet when I use `vagrant up` or `vagrant halt`, the goodhosts vagrant plugin intervenes with an error:

```
❯ vagrant halt
==> default: Running action triggers before halt ...
==> default: Running trigger...
==> default: 
==> default: [vagrant-goodhosts] Removing hosts
==> default: [vagrant-goodhosts] Error adding some hosts, no IP was provided for the following hostnames: 
```

No goodhosts APIs were called, requested, or desired. The plugin should not be outputting anything or doing anything, and yet it does. This should not happen. The `vagrant-goodhosts` plugin should only run when the `vagrant-goodhosts` plugin is used. Even then, if there are no hosts to remove, it should not attempt to remove them

This is with v1.0.8 and v1.0.7

**Comment by Mte90** [comment]
Ideally I should check if there are goodhosts settings like `@machine.config.goodhosts.aliases` in https://github.com/goodhosts/vagrant/blob/2ada34a45e90cbe4e1dc08aa634d0f1d399541ba/lib/vagrant-goodhosts/Action/UpdateHosts.rb#L15 and execute the plugin.

**Comment by tomjn** [comment]
Noting that this is still an issue, I created #19 to try and address this but it needs to be tested
