### ISSUE TITLE
Hosts are added multiple times in Vagrant 2.2.14

### ISSUE THREAD

**Issue by tomjn** [goodhosts/vagrant#16]
Hook behaviour changed in 2.2.14, so now the plugin adds hosts multiple times rather than just once on a `vagrant up`, and likewise it tries to remove them multiple times

**Comment by Mte90** [comment]
I see the problem too, but I don't know how to fix that honestly.
As the code to execute it is using hooks https://github.com/goodhosts/vagrant/blob/master/lib/vagrant-goodhosts/plugin.rb

Maybe a solution is to implement something that assure that hooks are executed just once or see if there is a new api. 

Anyway I reported it https://github.com/hashicorp/vagrant/issues/12070 as this is not involving provisioners but hooks and probably broke a lot of plugins too.

**Comment by tomjn** [comment]
a flag somewhere needs setting to track if it's ran or not
