### ISSUE TITLE
Avoid changing the hosts file if the relevant hosts are already present

### ISSUE THREAD

**Issue by tomjn** [goodhosts/vagrant#22]
If a VM uses a domain but that domain has been manually added then it should not attempt to modify the hosts file

**Comment by luthermonson** [comment]
if the ip and host match something already in there we don't add it do we? i thought there was already a check in gh for that. if not that's an easy add

**Comment by Mte90** [comment]
no there isn't a check for that reason there was added also the clean command.

GH was adding multiple times the same rules for the same ip but adding another same domain.

**Comment by Mte90** [comment]
We can do this check from the vagrant plugin in this way:

```
require 'socket'
IPSocket::getaddress('www.google.com') #=> "74.125.79.147"
```

So it is needed to add this check with a loop for all the domain using the ip and in case of failure to execute goodhosts.
In this way there is not sudo or admin permission requests.

**Comment by tomjn** [comment]
this should be in the main branch now
