### ISSUE TITLE
Goodhosts is not removing its entries when halting the vm

### ISSUE THREAD

**Issue by theMikeD** [goodhosts/vagrant#23]
`/etc/hosts` at start

```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting. Do not change this entry.
##
127.0.0.1 localhost
255.255.255.255 broadcasthost
::1 localhost
fe80::1%lo0 localhost
```

Hosts file after `vagrant up`
```
::1 localhost
127.0.0.1 localhost
192.168.50.4 vvv.test rfa.test
255.255.255.255 broadcasthost
```

Hosts file after `vagrant halt`

```
::1 localhost
127.0.0.1 localhost
192.168.50.4 rfa.test vvv.test
255.255.255.255 broadcasthost
```

**Comment by Mte90** [comment]
Seems that the cleaning is not working I think that is an issue with goodhosts itself

**Comment by luthermonson** [comment]
what would be the calls to gh in this scenario? 2x calls to remove each host or 1x call to remove the ip?

**Comment by theMikeD** [comment]
I have no idea. I figured if gh was the one doing the inserting, it would be capable of undoing what it did? Or did I mis understand?

Is this more fallout from the forced clean option?

**Comment by Mte90** [comment]
I can confirm the issue is happening just with the plugin and not with the cli tool, with clean parameter.

**Comment by theMikeD** [comment]
To reproduce:

```shell
$ git clone https://github.com/Varying-Vagrant-Vagrants/VVV vm
$ cd vm
$ vagrant plugin install vagrant-goodhosts --local
```

At this point my hosts file contains
```
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting. Do not change this entry.
##
127.0.0.1 localhost
255.255.255.255 broadcasthost
::1 localhost
fe80::1%lo0 localhost
```

Next:

```shell
$ vagrant up --provision
```

hosts file now contains

```
::1 localhost
127.0.0.1 localhost
192.168.50.4 vvv.test one.wordpress.test two.wordpress.test
255.255.255.255 broadcasthost
```
restructured, comments removed, IPV6 removed.

Once provision is complete:

```shell
$ vagrant halt
```

When that is done, hosts file contains

```
::1 localhost
127.0.0.1 localhost
192.168.50.4 one.wordpress.test two.wordpress.test vvv.test
255.255.255.255 broadcasthost
```

**Comment by Mte90** [comment]
I can confirm that without clean the error is not happening.
