### ISSUE TITLE
Prevent repeated action executions

### ISSUE THREAD

**Issue by BR0kEN-** [goodhosts/vagrant#25]
Context:
- https://github.com/hashicorp/vagrant/issues/12070
- https://github.com/agiledivider/vagrant-hostsupdater/issues/187
- https://github.com/agiledivider/vagrant-hostsupdater/issues/193

**Comment by Mte90** [comment]
We already implemented a code few releases ago to avoid this issue.
I need to do some tests and see if this one is better (at first view seems a better refactoring of the code).

**Comment by BR0kEN-** [comment]
Yeah, this PR just maintains the higher copy-paste level from https://github.com/agiledivider/vagrant-hostsupdater. Feel free to close it.
