### ISSUE TITLE
Windows & maximum number of host aliases per line

### ISSUE THREAD

**Issue by ksere** [goodhosts/vagrant#28]
Hi!

It looks like Windows support only up to 9 aliases per line. 
More info on this [here](https://superuser.com/questions/932112/is-there-a-maximum-number-of-hostname-aliases-per-line-in-a-windows-hosts-file#answer-932113).
My VVV tries to fit in there around 70 😄 

Anyway we can have goodhosts break them down to multiple lines?

**Comment by Mte90** [comment]
This is a bug for the cli tool, the plugin is just a wrapper around it.

Can you open a ticket here -> https://github.com/goodhosts/cli
