### ISSUE TITLE
Problem installing this plugin

### ISSUE THREAD

**Issue by deimidis** [goodhosts/vagrant#29]
In a new vagrant installation, I cloned this repo and following instructions, I tried to install goodhosts plugin.

Installing the 'vagrant-goodhosts' plugin. This can take a few minutes...
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

conflicting dependencies net-ssh (>= 2.6.5) and net-ssh (= 6.2.0.rc1)
  Activated net-ssh-6.2.0.rc1
  which does not match conflicting dependency (>= 2.6.5)

  Conflicting dependency chains:
    net-ssh (= 6.2.0.rc1), 6.2.0.rc1 activated

  versus:
    net-scp (= 1.2.1), 1.2.1 activated, depends on
    net-ssh (>= 2.6.5)

  Gems matching net-ssh (>= 2.6.5):
    net-ssh-6.2.0.rc1

My system is Manjaro on testing branch. It worked some time ago on another Manjaro testing. If I understand, maybe I need to install net-ssh 2.6.5, but my system is trying to install a newer version.

Manjaro Testing branch
Vagrant vagrant-2.2.14-1
vvv: I just clone the repo today

**Comment by Mte90** [comment]
This doesn't involve VVV but is just an error on installing the plugin on your system.
I think that you don't have an updated Ruby version on your machine.

**Comment by deimidis** [comment]
Thanks, I'm using Ruby 2.7.2 on Manjaro (Arch based). I see there is a 3.0 version, but don't know if that's the problem. Is that package needed or requested by this plugin?

**Comment by Mte90** [comment]
Hi guillermo, is a long time since the last Mozilla event we met :-)
I am using ruby 1.7.1 and works on debian.

Looking on https://github.com/hashicorp/vagrant/issues/12202 seems an issue also on Archlinux and downgrading vagrant fix it. There is a pull request merged on vagrant so probably the next release will fix it.

**Comment by deimidis** [comment]
Hi Danielle, yes, long time, and I see you more and more in different github projects I use.

I just arrived to that issue and saw that you point it. I will try with that. Has to work, because I was using vvv with an old installation. Thanks again. I will close with this comment

**Comment by Mte90** [comment]
Ahahah yes, I am very involved with WordPress as core contributor and I am one of the VVV maintainers.
You can find me on the VVV slack instance for anything :-) https://varyingvagrantvagrants.org/docs/en-US/slack/

**Comment by deimidis** [comment]
I will wait for VAgrant update on Arch/Manjaro. I will need it next week or so, so before downgrading I will wait. BTW I'm using your glossary plugin too

**Comment by dag7dev** [comment]
The issue is still actual and it works if you downgrade, it doesn't if you don't unfortunately.

**Comment by Mte90** [comment]
This is a bug of vagrant and not of the plugin.
The right way is to ask to the vagrant plugin https://github.com/hashicorp/vagrant/issues/12202 to do a new release (the last one is from november 2020)
