### ISSUE TITLE
Broken multi-machine handling

### ISSUE THREAD

**Issue by BR0kEN-** [goodhosts/vagrant#30]
Reference: https://github.com/agiledivider/vagrant-hostsupdater/issues/198

#26 introduced a bug that caused hosts processing only for the first defined VM in a Vagrantfile (the problem exists only for multi-machine Vagrantfiles).

**Comment by Mte90** [comment]
Thanks for spotting this case, I will do a new release during the week with the patch :-)

**Comment by Mte90** [comment]
New release available :-)
