### ISSUE TITLE
Fails to set hosts when used in a path with a space

### ISSUE THREAD

**Issue by atimmer** [goodhosts/vagrant#32]
The plugin fails when used in a path that includes a space in a folder name. For example, I have vagrant-local located in `Users/anton/Local Sites/vagrant-local`. When doing a `vagrant up` or `vagrant halt` the plugin fails with this error:

```
==> default: [vagrant-goodhosts] Issue executing goodhosts CLI: sudo: /Users/anton/Local: command not found
==> default: [vagrant-goodhosts] Cli path: /Users/anton/Local Sites/vagrant-local/.vagrant/plugins/gems/2.6.6/gems/vagrant-goodhosts-1.0.13/lib/vagrant-goodhosts/bundle/cli_osx
==> default: [vagrant-goodhosts] Check the readme at https://github.com/goodhosts/vagrant#passwordless-sudo
```

Because I see `/Users/anton/Local` in the first line I assume it fails because the space in the folder name.

## Workaround

Move `vagrant-local` to a path that doesn't include a space in one of it's folder. I have tested this and it works.

**Comment by Mte90** [comment]
https://github.com/goodhosts/vagrant/commit/0d210412600dbf0231852281876ee9a6e0f153af

Fixed I am doing a new release, thanks for spotting the issue!
