### ISSUE TITLE
Where Should One Add config.goodhosts.remove_on_suspend?

### ISSUE THREAD

**Issue by davidshq** [goodhosts/vagrant#33]
I added config.goodhosts.remove_on_suspend = false to the bottom of my config/config.yml file and this causes Vagrant to say it isn't a valid config file. Where should this config option be placed?

**Comment by Mte90** [comment]
This plugin is not just for VVV.

That is a Ruby code and you cannot insert in the a yaml file as you did.
You need to edit the `vagrantfile` or in the case of VVV check how works the `customfile`. https://varyingvagrantvagrants.org/docs/en-US/references/vagrantfile/
