### ISSUE TITLE
Passwordless sudo what path

### ISSUE THREAD

**Issue by janw-me** [goodhosts/vagrant#4]
I've created the snippet `sudo visudo -f /etc/sudoers.d/vagrant_goodhosts`
I can't figure out the `[the-path]` I tried the root the Vagrantfile is in `/home/janw-me/Webdev/vagrant-local`, I tried `/etc/hosts`
But these don't work, I don't know what else could an option, I don't see a path in cli output

Can you explain what the path should be?

I'm running [vvv](https://github.com/Varying-Vagrant-Vagrants/VVV) on my Ubuntu host machine.

In older version of vvv it used hostupdater, and it also had a [passwordless](https://github.com/agiledivider/vagrant-hostsupdater#linuxos-x-passwordless-sudo) tweak, I had that working

**Comment by Mte90** [comment]
The path is written in the Vagrant output if there are errors (in red) with a reference to the readme.

As this plugin use a different binaries require permissions.

As example in my computer:
```mte90 ALL=(root) NOPASSWD: /home/mte90/.vagrant.d/gems/2.6.6/gems/vagrant-goodhosts-1.0.1/lib/vagrant-goodhosts/bundle/cli```

**Comment by janw-me** [comment]
I don't see any errors.
![2020-07-28_18-09](https://user-images.githubusercontent.com/1026882/88691671-7404db00-d0fd-11ea-857c-11ec0134dbb3.png)

I double checked even after removing the `/etc/sudoers.d/vagrant_goodhosts` file I always get asked for the password. and I don't see any error.
I tried `vagrant up | halt | suspend` no errors, always need password.

Some manual digging I found the path added it and it works.
If I can provide more information that can help to debug this let me know.

**Comment by Mte90** [comment]
So the function is at https://github.com/goodhosts/vagrant/blob/master/lib/vagrant-goodhosts/GoodHosts.rb#L147 and is executed when there is an error reported by the cli tool.
So if you are asked to put manually the password it isn't count as an error.

**Comment by Mte90** [comment]
I am releasing a new version, now the command is executeds just once so for the password is more simple then insert more times and improved a bit the readme.

**Comment by janw-me** [comment]
I reinstalled on a new laptop and I stilll had this issue.
1) when the script asks for the password cancel the process (`ctrl+c`) to force an error..
2) example path: `%sudo ALL=(root) NOPASSWD: /path/to/box/.vagrant/plugins/gems/2.6.7/gems/vagrant-goodhosts-1.0.15/lib/vagrant-goodhosts/bundle/cli`

**Comment by Mte90** [comment]
I don't understand the problem. Basically the sudo is not working for you also if you added the config?

If the config file exist and the path is right everything should works. 
I am on debian and in my case the plugin is installed on the user `/home/mte90/.vagrant.d/gems/2.6.6/gems/vagrant-goodhosts-1.0.15/lib/vagrant-goodhosts/bundle/cli`

My config is `ALL ALL=(root) NOPASSWD: /home/mte90/.vagrant.d/gems/2.6.6/gems/vagrant-goodhosts-1.0.15/lib/vagrant-goodhosts/bundle/cli`

**Comment by janw-me** [comment]
The problem is finding the path.

When I cleanly install vvv on a freshly installed ubuntu and I up/halt/suspend it will ask for the password. This is not an error. But it is annoying.
So I want add it to the sudoer file. The instructions in the readme say to find the path based on the error.
But -like the screenshot I posted before- there is not error, so there is no path shown.
The normal usage doesn't trigger an error, which makes it near impossible to find the path.

My previous comment is pretty much a note on alternative way to help find this path.

> I am on debian and in my case the plugin is installed on the user.
Check, I understand you have the plugin installed globally, and that's why you path is so different.

**Comment by Mte90** [comment]
Ok so the path is not printed when asks the password. Probably if you write the wrong password it will print the full path.
The code check if the sudo command return an error in this way can print the log https://github.com/goodhosts/vagrant/blob/master/lib/vagrant-goodhosts/GoodHosts.rb#L155

**Comment by janw-me** [comment]
> Probably if you write the wrong password it will print the full path.
That probably will work, also ctrl+c cancelling the process works.

Is there a better way to document this? A less technical person will not be able to guess this/dig in closes issues.

**Comment by Mte90** [comment]
You are right, the problem is that is not possible to detect from Ruby when a command asked for input.
So I cannot detect when sudo is not configured. Also I think that is not the case to show always the path to the cli tool.
The readme specify `The command path is printed when there are errors with sudo.` so I don't know how to document better to the user.

**Comment by Mte90** [comment]
I will update the readme, thanks for the hints.

**Comment by Mte90** [comment]
added those info in the readme
