### ISSUE TITLE
vagrant-goodhosts stalls when the /etc/hosts file has too many entries

### ISSUE THREAD

**Issue by conradolandia** [goodhosts/vagrant#43]
I block malware sites and ads from the internet using a large `hosts` file (600.000+ lines), redirecting all these bad hosts to 0.0.0.0. When I try to use goodhosts, it just freezes and whatever process I was on won't go on. If I remove most of the entries form /etc/hosts, the process completes without problems. Is this a bug or expected behavior?

**Comment by tomjn** [comment]
@Mte90 how do you know it's goodhosts itself that's stalling?

**Comment by Mte90** [comment]
So I had in the past a lot of hosts inside the file and goodhosts was parsing all of them for rewriting (clean as example) and this was changing the whole file and delay everything.
As the plugin just call the command with the hosts we need to add the stall should be on the goodhosts side as need to parse 600000~ urls for cleaning and look if there are duplicates and so on. 

At the end I removed everything on my hosts file and there are no issues anymore, also as goodhosts development is stalled I didn't opened a ticket for it.

**Comment by tomjn** [comment]
@Mte90 that's cleaning, we don't clean anymore on VVV where this was first seen, haven't for a long time.

But even ignoring that, you've shared an anecdote, no actual data has been shared proving it, just assumptions. Instead, @conradolandia should be able to test the theory by trying to add a host with the goodhosts CLI to see if it still hangs. If so, it's the CLI. If not, it's the vagrant plugin.

You're also assuming they have the latest version of the plugin, we don't know that

**Comment by tomjn** [comment]
@conradolandia grab the latest goodhosts from https://github.com/goodhosts/cli/releases and try to use it to add a host, e.g. `goodhosts add 127.0.0.1 example.test`

**Comment by tomjn** [comment]
and run `vagrant plugin list --local` to get the version of the plugin

**Comment by Mte90** [comment]
How much times takes? maybe is the ruby api that has issues with the timeout or similar.

**Comment by conradolandia** [comment]
```shell
~ wc -l /etc/hosts
610748 /etc/hosts
~ time sudo goodhosts add 127.0.0.1 loquesea.test
hosts entry added: 127.0.0.1 loquesea.test
sudo goodhosts add 127.0.0.1 loquesea.test  3,61s user 0,37s system 156% cpu 2,545 total
```

**Comment by YouJiacheng** [comment]
Can we use `system` directly as suggested by following chart?
![](https://i.stack.imgur.com/1Vuvp.png)

**Comment by Mte90** [comment]
We need the output of the command including also stderr https://github.com/goodhosts/vagrant/blob/main/lib/vagrant-goodhosts/GoodHosts.rb#L138

**Comment by Mte90** [comment]
We already use popen3 https://github.com/goodhosts/vagrant/blob/main/lib/vagrant-goodhosts/GoodHosts.rb#L113 so I need to know what are the differences between the two methods.

**Comment by tomjn** [comment]
What’s the reason for the change? Calling the CLI works already so I don’t
see any improvements to be had here and it sounds like it already uses the
optimum method

**Comment by YouJiacheng** [comment]
`capture3` is a light weight wrapper  of block form popen, which waits for the process when it returns.
Okay I found that `wait_thr.value` also waits for the termination of the process. So why this issue is not closed?

**Comment by YouJiacheng** [comment]
https://www.rubydoc.info/stdlib/open3/Open3.popen3
> You should be careful to avoid deadlocks. Since pipes are fixed length buffers, Open3.popen3(“prog”) {|i, o, e, t| o.read } deadlocks if the program generates too much output on stderr. You should read stdout and stderr simultaneously (using threads or IO.select). However, if you don't need stderr output, you can use Open3.popen2. If merged stdout and stderr output is not a problem, you can use Open3.popen2e. If you really need stdout and stderr output as separate strings, you can consider Open3.capture3.

**Comment by YouJiacheng** [comment]
Not only the stderr, since we never read from stdout before join the waiting thread(`wait_thr.value`), too much output on stdout will cause deadlock as well.
Even worse, we don't close stdin, stdout and stderr, which is required by docs: "stdin, stdout and stderr should be closed explicitly in this form."
```ruby
stdin, stdout, stderr, wait_thr = Open3.popen3([env,] cmd... [, opts])
pid = wait_thr[:pid]  # pid of the started process
...
stdin.close  # stdin, stdout and stderr should be closed explicitly in this form.
stdout.close
stderr.close
exit_status = wait_thr.value  # Process::Status object returned.
```

**Comment by YouJiacheng** [comment]
According to "When I try to use goodhosts, it just freezes and whatever process I was on won't go on.", it seems a deadlock. However, the cli never output too much.
Anyone can reproduce the issue?

**Comment by YouJiacheng** [comment]
Since `capture3` is more robust than `popen3`, can we use it instead? Hope that can solve this issue.

**Comment by Mte90** [comment]
I am not able to reproduce the issue but I think that to test it is required a big hosts file that take a lot to parse it.

**Comment by tomjn** [comment]
@Mte90 I'm not sure why a big hosts file would matter here as this code isn't inside goodhosts, it's the vagrant plugin that calls it, no host files are being touched by ruby itself

**Comment by Mte90** [comment]
The problem is the execution of the cli command that takes a while and probably this freeze something in vagrant. In our case the output is very tiny anyway from this so I think that it is something to be improved on the cli side and not on the vagrant side.

**Comment by tomjn** [comment]
If the user walks away and comes back to a sudo or UAC prompt 5 minutes
later that’s no different to goodhosts taking 5 minutes to handle a massive
hosts file so this has to be handled at this end too if it’s a problem
