### ISSUE TITLE
Windows maximum aliases per line

### ISSUE THREAD

**Issue by hegemanjr** [goodhosts/vagrant#49]
As seen here https://superuser.com/questions/932112/is-there-a-maximum-number-of-hostname-aliases-per-line-in-a-windows-hosts-file, there is a maximum of nine aliases per line in the hosts file on Windows.

I am often beyond that maximum of nine aliases in the VVV environments I use, meaning some of my sites don't work without manually splitting the aliases into multiple lines.

Assuming that I'm not the only one running into this, I would like to request a feature that automatically splits the aliases into multiple lines if there are more than nine.

Thanks!

**Comment by Mte90** [comment]
You need to open a ticket on the cli tool that this plugin uses of this project -> https://github.com/goodhosts/cli/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

This plugin is just a wrapper around this tool and we can't do anything for this.
