### ISSUE TITLE
getIps has no failure handling and returns in the wrong location

### ISSUE THREAD

**Issue by tomjn** [goodhosts/vagrant#5]
https://github.com/goodhosts/vagrant/blob/master/lib/vagrant-goodhosts/GoodHosts.rb#L7

There are 2 main issues:

 - if no IPs are found, then an empty array is passed in to the goodhosts CLI, which might result in an error being passed due to the first host being interpreted as the IP address
 - no checking for empty IPs when executing the cli occurs
 - The `return` statement is not at the end of the method, but inside the foreach, so only the first networks IP is used

**Comment by Mte90** [comment]
I will release a new version on monday.
