### ISSUE TITLE
Duplicated domains

### ISSUE THREAD

**Issue by mathieuhays** [goodhosts/vagrant#9]
Hi,

I'm using this plugin with the [VVV Project](https://github.com/Varying-Vagrant-Vagrants/VVV) on Mac OS 10.15.6
Vagrant Version: 2.2.10
VirtualBox Version: 6.1.12
Plugin Version: 1.0.4

On `vagrant halt` I'm getting this:
```
==> default: [vagrant-goodhosts] Removing hosts
==> default: [vagrant-goodhosts] - found entry for: 192.168.50.4 vvv
==> default: [vagrant-goodhosts] - found entry for: 192.168.50.4 vvv.test
```
But once the task is complete these entries are still in my `/etc/hosts` file.

On `vagrant up` I'm getting this:
```
==> default: [vagrant-goodhosts] Checking for host entries
==> default: [vagrant-goodhosts] - found entry for: 192.168.50.4 vvv
==> default: [vagrant-goodhosts] - found entry for: 192.168.50.4 vvv.test
```
Once the task is complete these entries are added on top of the one that weren't removed, so each domain are effictively duplicated.

So if I manually remove these entries and then cycle through vagrant up / halt 3 times, I'll have each domain appearing 3 times each on the line of my VVV instance IP.

I noticed this issue because Safari wasn't working with my local domains, I suspect it's because the host file entry line got too long. It works fine even when there are a couple of duplicates but once the line gets too long Safari returns a server not found error.

Hope that makes sense

**Comment by Mte90** [comment]
I think that depends on https://github.com/goodhosts/cli/issues/12

I am waiting a release of the cli tool so I can release a new version

**Comment by luthermonson** [comment]
sorry @Mte90 ill do it this weekend

**Comment by luthermonson** [comment]
https://github.com/goodhosts/cli/releases/tag/v.1.0.5
you can add --clean to the add/remove commands now with the new release.
